seriousme/fastify-openapi-glue

- examples/generatedProject/package.json
- lib/parser.v2.js
- test/test-plugin.v2.js
- test/test-swagger.v2.checksums.json
- test/test-swagger.v2.json
Added testing for V2 and updated checksums and generated project
> Noparam v2

- CHANGES.md
- README.md
- index.js
- test/test-plugin.v3.js
> Add prefix option

- README.md
Added notes section to README.md to clarify plugin behaviour
> Added notes section 

- CHANGES.md
- examples/generatedProject/package.json
- package-lock.json
- package.json
- fastify-plugin   ^1.5.0  →   ^1.6.0
- fastify          ^2.2.0  →   ^2.5.0
- tap             ^14.0.0  →  ^14.2.5
> updated dependencies

- lib/parser.v3.js
- test/test-openapi-v3-generic-path-items.json
- test/test-plugin.v3.js
see https://github.com/seriousme/fastify-openapi-glue/issues/52
> Improve v3 operations parsing

- index.js
> added ajv nullable

- CHANGES.md
- README.md
- index.js
- test/test-openapi.v3.json
- test/test-plugin.v3.js
> No additional opt

- index.d.ts
> add typescript typings for fastify-openapi-glue

- index.js
> fix losing of scope in service request

- README.md
- examples/generatedProject/index.js
- examples/generatedProject/package.json
- index.d.ts
- lib/templates/index.js
- test/test-swagger-noBasePath.v2.checksums.json
- test/test-swagger.v2.checksums.json
Updating the README, and some other minor stuff
> finalize Security Handlers

- examples/generatedProject/package.json
- index.js
- package-lock.json
- package.json
Fastify 3.0.0 has a breaking change on configuration of schema validation,see https://github.com/fastify/fastify/pull/2023
> migrated to Fastify 3.0.0

- examples/generatedProject/service.js
- examples/generatedProject/test/test-plugin.js
- lib/parser.v2.js
- lib/parser.v3.js
- lib/parserBase.js
- test/service.js
- test/test-openapi.v3.json
- test/test-plugin.v2.js
- test/test-plugin.v3.js
- test/test-swagger.v2.checksums.json
- test/test-swagger.v2.json
as discussed in https://github.com/seriousme/fastify-openapi-glue/issues/128
> feature: add support for x- props

- CHANGELOG.md
- examples/generatedProject/index.js
- examples/generatedProject/package.json
- lib/templates/index.js
- package.json
- test/test-swagger-noBasePath.v2.checksums.json
- test/test-swagger.v2.checksums.json
- Fixed missing slash in generator template
- Updated dependencies:
- ajv             ^6.12.4  →  ^6.12.5   
- fastify-plugin   ^2.3.1  →   ^2.3.4   
- swagger-parser  ^10.0.1  →  ^10.0.2   
- fastify          ^3.2.1  →   ^3.4.1
> Fix slash in indexjs template

- .taprc
- index.js
- package.json
- test/test-plugin.v3.js
Improved:
- nodejs version detection
- tap handling of ESM
- skipping of tests
- ternary expresion instead of full if-then-else
> improve ESM handling

- index.js
- lib/oai-formats.js
- package-lock.json
- package.json
- test/test-oai-formats.js
- test/test-openapi.v3.json
- test/test-plugin.v3.js
Removing this dependency should make the migration to Ajv 7.x easier
> Removed dependency on ajv-oai

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
- test/test-oai-formats.js
- test/test-petstore-example.js
Ajv 7.x is a breaking release so beware
> Upgraded to Ajv 7.x

- index.js
- removed the workaround because fastify has a native fix since version 3.2.1
- some minor refactoring to increase readability
> remove hasContentTypeParser workaround

- .taprc
- examples/generatedProject/package.json
- examples/generatedProject/test/test-plugin.js
- lib/templates/test-plugin.js
- package-lock.json
- package.json
- test/test-petstore-example.js
- test/test-plugin.v2.js
- test/test-plugin.v3.js
- test/test-securityHandlers.v2.js
- test/test-securityHandlers.v3.js
- test/test-swagger-noBasePath.v2.checksums.json
- test/test-swagger.v2.checksums.json
Removed esm from .taprc
Reworked strictlyEqual to Equal as per tap warnings
> Update to Tap 15.0.1

- CHANGELOG.md
- examples/generatedProject/package.json
- lib/oai-formats.js
- package.json
- test/test-oai-formats.js
Fix the byte validation error as reported in #205.
> Fix byte validation

- index.js
- test/test-petstore-example.js
> feat(schema): formats ajv error to include property names

- lib/Parser.v3.js
- test/test-openapi.v3.json
fixes the regression found in #231
> fix-empty-body-content

- package-lock.json
> fix browserslist

- lib/ParserBase.js
- test/test-parser-base.js
- test/test-swagger.v2.checksums.json
get /user/{name} becomes getUserByName as it used to
> fix makeOperationId

- lib/securityHandlers.js
- test/test-debuglogging.js
- added test for debug logging
- fixed incorrect error message in debug log
> fix (log):  fix debug log of securityHandler errors

- package-lock.json
- package.json
update dependencies:
@seriousme/openapi-schema-validator   ^1.3.0  →   ^1.6.0     
ajv                                   ^8.6.2  →   ^8.9.0     
fastify-plugin                        ^3.0.0  →   ^3.0.1     
c8                                    ^7.8.0  →  ^7.11.0     
fastify                              ^3.20.2  →  ^3.27.1     
fastify-cli                          ^2.13.0  →  ^2.15.0     
tap                                  ^15.0.9  →  ^15.1.6
> update dependencies AJV 8.9.0

- CHANGELOG.md
- examples/generatedProject/package.json
- package-lock.json
- package.json
- Updated dependencies:
@seriousme/openapi-schema-validator   ^2.0.0  →   ^2.0.2     
fastify                              ^3.28.0  →  ^3.29.0     
fastify-cli                          ^2.15.0  →   ^3.0.1     
tap                                  ^16.1.0  →  ^16.2.0
> Update dependencies 

- CHANGELOG.md
- index.js
This PR fixes the `defaultAJV` option
> Fix defaultAJV

- index.d.ts
- index.js
- test/test-import-plugin.cjs
- test/test-import-plugin.js
This PR fixes #348 and adds test to prevent regression.
> fix: fix cjs import

- CHANGELOG.md
- package-lock.json
- package.json
fastify       ^4.0.0  →   ^4.0.3     
fastify-cli   ^4.0.0  →   ^4.1.1     
tap          ^16.2.0  →  ^16.3.0
> Update dependencies incl. Fastify 4.0.3

- docs/securityHandlers.md
- examples/generatedProject/package.json
- lib/securityHandlers.js
- test/security.js
- test/test-securityHandlers.v3.js
In response to #357. See SECURITY.md for an explanation.
> feat: allow custom status code in security handlers

- index.js
Restructured index.js for readability
> chore: restructure index.js

- test/test-generate-project.js
- test/test-generator.js
Refactor from promises to async/await
> chore: cleanup generator tests

- CHANGELOG.md
- package-lock.json
- package.json
- updated dependencies:
- @seriousme/openapi-schema-validator   ^2.0.2  →   ^2.0.3
- fastify-plugin                        ^4.0.0  →   ^4.2.1
- c8                                   ^7.11.3  →  ^7.12.0
- eslint                               ^8.18.0  →  ^8.23.0
- eslint-plugin-prettier                ^4.1.0  →   ^4.2.1
- fastify                               ^4.2.0  →   ^4.5.3
- fastify-cli                           ^5.0.0  →   ^5.4.1
> chore: update dependencies

- examples/generatedProject/package.json
- examples/generatedProject/test/test-plugin.js
- lib/Parser.js
- lib/Parser.v2.js
- lib/Parser.v3.js
- lib/ParserBase.js
- lib/templates/js/test-plugin.js
- package-lock.json
- test/test-debuglogging.js
- test/test-fastify-recursive.js
- test/test-fastify.js
- test/test-generate-project.js
- test/test-generator.js
- test/test-openapi-v3-recursive.json
- test/test-parser-base.js
- test/test-petstore-example.js
- test/test-plugin.v2.js
- test/test-plugin.v3.js
- test/test-recursive.v3.js
- test/test-securityHandlers.v2.js
- test/test-securityHandlers.v3.js
- test/test-swagger-noBasePath.v2.checksums.json
- test/test-swagger.v2.checksums.json
> fix:  handle recursive schema correctly 

- examples/generatedProject/package.json
- package.json
This PR adds a default export to package.json
> Add default export to package.json

- README.md
- examples/generatedProject/package.json
- index.js
- lib/Parser.v2.js
- lib/Parser.v3.js
- test/test-plugin.v3.js
This PR extends the operationResolver with method and path as discussed in #423
> Extend operationResolver with method and path

- CHANGELOG.md
- examples/generatedProject/package.json
- lib/Parser.v3.js
- package-lock.json
- package.json
- test/service.js
- test/test-openapi.v3.json
- test/test-plugin.v3.js
This PR should fix #447
It also updates dependencies
> fix: fix querystring array

- CHANGELOG.md
- examples/generatedProject/index.js
- examples/generatedProject/package.json
- examples/petstore/index.js
- lib/templates/js/index.js
- lib/templates/js/package.json
- package-lock.json
- package.json
- test/test-petstore-example.js
- test/test-swagger-noBasePath.v2.checksums.json
- test/test-swagger.v2.checksums.json
This PR fixes the error found in #457.
> Fixed options on petstore example

- index.js
- lib/Parser.v2.js
- lib/Parser.v3.js
- lib/ParserBase.js
- lib/securityHandlers.js
- Replace foreach by for-in and for-of
- Simplify the main structure of index.js
> chore: refactor index.js

- README.md
- index.d.ts
- index.js
- test/test-custom-route-options.js
> feat: return route options for operationResolver

- CHANGELOG.md
- docs/securityHandlers.md
- examples/generatedProject/security.js
- index.js
- lib/templates/security.js
- test/test-securityHandlers.v2.js
- test/test-securityHandlers.v3.js
- test/test-swagger-noBasePath.v2.checksums.json
- test/test-swagger.v2.checksums.json
> Backport async security initialize from 4.4.0

- examples/generated-javascript-project/package.json
- examples/generated-javascript-project/test/test-plugin.js
- examples/generated-standaloneJS-project/test/test-plugin.js
- lib/templates/js/test-plugin.js
- lib/templates/standaloneJS/test-plugin.js
- test/test-cookie-param.v3.js
- test/test-custom-route-options.js
- test/test-fastify-recursive.js
- test/test-fastify.js
- test/test-petstore-example.js
- test/test-plugin.v2.js
- test/test-plugin.v3.js
- test/test-recursive.v3.js
- test/test-securityHandlers.v2.js
- test/test-securityHandlers.v3.js
- test/test-swagger-noBasePath.v2.javascript.checksums.json
- test/test-swagger-noBasePath.v2.standaloneJS.checksums.json
- test/test-swagger.v2.javascript.checksums.json
- test/test-swagger.v2.standaloneJS.checksums.json
- test/test-warnings.js
Most test don't test anything because tests ends before the async operation.
> test: wait until the end of the test

- examples/generated-javascript-project/package.json
- package.json
Fix biome linting issue and add lint checking to npm test
> fix biome linting issue

- examples/generated-javascript-project/package.json
- lib/Parser.v3.js
- test/test-openapi.v3.content.json
- test/test-plugin.v3.content.js
This should fix https://github.com/seriousme/fastify-openapi-glue/issues/603
> fix: Support "content" field for query string

- CHANGELOG.md
- package-lock.json
- package.json
- chore: updated dependencies
- @seriousme/openapi-schema-validator  ^2.2.4  →  ^2.2.5
> Update dependencies: @seriousme/openapi-schema-validator 2.2.5

- .github/workflows/nodejs-ci.yml
- biome.jsonc
- index.d.ts
- index.spec-d.ts
- package-lock.json
- package.json
- tsconfig.json
This PR improves index.d.ts testing.
> feat(dev): add index.d.ts tests
