lib/parser.js
test/test-generate-project.js
test/test-plugin.v3.js

Hi! 
A small fix to allow OpenAPI 3.0.1 files to be used as soon as they are supported by [swagger-parser](https://github.com/BigstickCarpet/swagger-parser/blob/master/lib/index.js#L61). 
Best!

OpenAPI v3.0.x support

---

lib/parser.js

If `swagger-parser` throws an error, the error message is logged to the console.

add logging to parser error

---

CHANGES.md
examples/generatedProject/package.json
package.json

ajv              ^6.11.0  →   ^6.12.0 
fastify-plugin    ^1.6.0  →    ^1.6.1 
minimist          ^1.2.0  →    ^1.2.5 
swagger-parser    ^9.0.0  →    ^9.0.1 
fastify          ^2.11.0  →   ^2.13.0 
fastify-cli       ^1.3.0  →    ^1.5.0 
tap             ^14.10.6  →  ^14.10.7

Updated dependencies

---

README.md
index.d.ts
index.js
test/test-openapi.v3.json
test/test-openapi.v3.yaml
test/test-plugin.v3.js

Hi there @seriousme.  How do you feel about a change like this to allow AJV to be configured?  Fastify allows its default AJV instance to be configured by specifying`ajv.customOptions` in the Fastify options, but since fastify-openapi-glue overrides the default schemaCompiler, those options get overwritten.

Add ability to pass options through to AJV

---

index.js

If used with recursive schema (Generic Tree structure, linked list, etc) current code will fail with 
```cmd
'Maximum call stack size exceeded'
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:29:30)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats (node_modules/fastify-openapi-glue/index.js:35:7)
› stripResponseFormats …
```

Fix stripResponseFormats for recursive schemas

---

lib/parser.v3.js

Hi @seriousme -- is it possible to remove this console log statement?  Now that I've added an API endpoint that returns 'text/plain', this log statement is making my test suite quite noisy.  Thanks!

Remove noisy console log statement

---

index.js
test/test-plugin.v2.js
test/test-plugin.v3.js

I thought it would be useful if errors thrown within the security handlers could be captured and used further down the request chain.
For example, someone may want to pass more specific auth reasons back to the API client as to why authentication failed. In this case, they could use `fastify.setErrorHandler` to grab the specific error messages and return them as part of the response.
If this looks ok, I can also throw some readme updates in.

Enable passthrough of security handler errors

---

README.md
docs/securityHandlers.md
examples/generatedProject/security.js
index.js
lib/parser.v2.js
lib/parser.v3.js
lib/parserBase.js
lib/securityHandlers.js
lib/templates/security.js
test/security.js
test/service.js
test/test-openapi.v3.json
test/test-plugin.v2.js
test/test-plugin.v3.js
test/test-securityHandlers.v2.js
test/test-securityHandlers.v3.js
test/test-swagger-noBasePath.v2.checksums.json
test/test-swagger.v2.checksums.json
test/test-swagger.v2.json

You can specify your own securityHandlers with the `securityHandlers` option.
If the provided object has an `initialize` function then fastify-openapi-glue will call this function with the `/components/securitySchemes` property (v3) or the `/securityDefinitions` property (v2) of the specification provided.
In the petstore example specification there is a section:
```json
"/pet": {
"post": {
...
"summary": "Add a new pet to the store",
"description": "",
"operationId": "addPet",
...
"security": [
{
"petstore_auth": [
"write:pets",
"read:pets"
]
}
],
```
If you provide a securityHandler called `petstore_auth` then it will be called as `petstore_auth(request,reply, params)` where request and reply will be fastify request and reply objects and params contains `["write:pets", "read:pets"]`.

add securityHandlers parameters

---

index.js
package.json
test/service.mjs
test/test-plugin.v3.js

This PR adds ES6 Module support.
You can now use ES6 modules for `service`  and `securityHandlers` if you are using Nodejs >= 14

Add ES6 module support

---

lib/Parser.v3.js
test/service.js
test/test-openapi.v3.json
test/test-plugin.v3.js

This PR adds support for "explode" property on "in:query" parameters
As [per specification](https://spec.openapis.org/oas/v3.1.0#fixed-fields-9): 
explode | boolean | When this is true, parameter values of type array or object generate separate parameters for each value of the array or key-value pair of the map. For other types of parameters this property has no effect. When style is form, the default value is true. For all other styles, the default value is false.
-- | -- | --
The specification is not very clear on what the "For other types of parameters this property has no effect. " means.
For now we assume it only applies to "in:query" as that would make most sense.

add support for exploding querystring parameter

---

lib/Parser.js
package-lock.json
package.json
test/test-plugin.v2.js
test/test-plugin.v3.js

By integrating @seriousme/openapi-schema-validator as a replacement for @apidevtools/swagger-parser we lose a large number of dependencies and add support for OpenApi 3.1.

integrate  openapi-schema-validator

---

CHANGELOG.md
examples/generatedProject/package.json
package-lock.json
package.json

- Deprecation of Nodejs < 14 
- Added Nodejs 18 to CI
- Updated dependencies:
@seriousme/openapi-schema-validator   ^1.6.0  →   ^1.7.1   
ajv                                   ^8.9.0  →  ^8.11.0     
minimist                              ^1.2.5  →   ^1.2.6     
fastify                              ^3.27.0  →  ^3.28.0     
tap                                  ^15.1.6  →  ^16.0.1

Update dependencies AJV 8.11

---

CHANGELOG.md
index.d.ts

Fix the typescript definition that was changed incorrectly in 2.7.0

Fix: use FastifyPluginAsync

---

README.md
lib/Parser.v2.js
lib/Parser.v3.js
test/test-openapi.v3.json
test/test-plugin.v2.js
test/test-plugin.v3.js
test/test-swagger.v2.checksums.json
test/test-swagger.v2.json

I recently came across a scenario where being able to add things to a route's `config` property from the API spec would be useful. (My case was specifically regarding the use of [fastify-raw-body](https://github.com/Eomm/fastify-raw-body).)
I implemented this as an extension `x-fastify-config` that can be added to an operation spec. I still need to update the readme as part of this PR, but wanted to get any feedback on whether this is something the community feels is beneficial as well as whether the approach is acceptable.

feat(route): allow passing route config in api spec

---

CHANGELOG.md
examples/generatedProject/package.json
package-lock.json
package.json
test/test-plugin.v2.js
test/test-plugin.v3.js

This PR updates dependencies and fixes
```
[FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.
```
warnings in test cases.

Fix fastify test warnings

---

index.d.ts

operationResolver Typescript definitions to match new parameters

fix: operationResolver Typescript definitions to match new parameters

---

README.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
package-lock.json
package.json
test/test-plugin.v2.js
test/test-plugin.v3.js

As discussed in #472 
Request.context will be deprecated in fastify 5.x, see:
https://github.com/fastify/fastify/blob/be137713136ba5f7bd4c22805ebc501b3412565f/lib/warnings.js#L24
This PR adjusts the docs and fixes both tests that relied on `route.context`.

fix: change Context.schema to routeSchema

---

CHANGELOG.md
examples/generated-javascript-project/package.json
examples/generated-javascript-project/test/test-plugin.js
examples/generated-standaloneJS-project/test/test-plugin.js
lib/templates/js/test-plugin.js
lib/templates/standaloneJS/test-plugin.js
test/test-cli.js
test/test-custom-route-options.js
test/test-debuglogging.js
test/test-fastify-cli.js
test/test-fastify-recursive.js
test/test-fastify.js
test/test-generate-project.js
test/test-generator.js
test/test-import-plugin.cjs
test/test-import-plugin.js
test/test-parser-base.js
test/test-petstore-example.js
test/test-plugin.v2.js
test/test-plugin.v3.js
test/test-recursive.v3.js
test/test-securityHandlers.v2.js
test/test-securityHandlers.v3.js
test/test-swagger-noBasePath.v2.javascript.checksums.json
test/test-swagger-noBasePath.v2.standaloneJS.checksums.json
test/test-swagger.v2.javascript.checksums.json
test/test-swagger.v2.standaloneJS.checksums.json

Due to a bug in Node 16 we can't remove Tap in full, however it has been removed from all individual tests.
As soon as Node 16 is EOL we can remove Tap from the list of dependencies

Replace Tap by Node Test

---

CHANGELOG.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
lib/Parser.v2.js
lib/Parser.v3.js
lib/ParserBase.js
package-lock.json
package.json
test/test-plugin.v2.js
test/test-swagger-v2-generic-path-items.json

This PR fixes #504 and updates the following dependencies:
- c8               ^8.0.0  →   ^8.0.1
- fastify         ^4.17.0  →  ^4.21.0
- fastify-cli      ^5.7.1  →   ^5.8.0
- fastify-plugin   ^4.5.0  →   ^4.5.1
- tap             ^16.3.6  →  ^16.3.8

fix: make Swagger generic parameters work

---

CHANGELOG.md
examples/generated-javascript-project/package.json
examples/generated-javascript-project/service.js
examples/generated-javascript-project/test/test-plugin.js
examples/generated-standaloneJS-project/index.js
examples/generated-standaloneJS-project/service.js
examples/generated-standaloneJS-project/test/test-plugin.js
lib/Parser.v2.js
test/test-plugin.v2.js

This fixes #506 and adds the schema fields mentioned there to the V2 parser.

fix: make additional validation for v2 non-body parameters work

---

.taprc
README.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
lib/templates/js/package.json
lib/templates/standaloneJS/package.json
package-lock.json
package.json
test/test-custom-route-options.js
test/test-import-plugin.cjs
test/test-plugin.v2.js
test/test-plugin.v3.js
test/test-swagger-noBasePath.v2.javascript.checksums.json
test/test-swagger-noBasePath.v2.standaloneJS.checksums.json
test/test-swagger.v2.javascript.checksums.json
test/test-swagger.v2.standaloneJS.checksums.json

- With the EOL of Node 16 we can remove Tap as test harness 
- Fastify has deprecated `routeConfig` and `routeSchema`, documentation and tests have been adjusted to replace them with `routeOptions.config` and `routeOptions.schema`.

fix: remove Tap and replace routeConfig and routeSchema

---

.gitignore
CHANGELOG.md
docs/securityHandlers.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/index.js
examples/generated-standaloneJS-project/package.json
examples/generated-standaloneJS-project/securityHandlers.js
lib/ParserBase.js
lib/securityHandlers.js
lib/templates/js/package.json
lib/templates/standaloneJS/package.json
package-lock.json
package.json
test/service.js
test/test-openapi.v3.json
test/test-securityHandlers.v3.js
test/test-swagger-noBasePath.v2.javascript.checksums.json
test/test-swagger-noBasePath.v2.standaloneJS.checksums.json
test/test-swagger.v2.javascript.checksums.json
test/test-swagger.v2.standaloneJS.checksums.json

- fix: securityHandlers fix for "AND" case
- fix: remove last traces of TAP from generator templates
- updated dependencies
- @biomejs/biome                        ^1.2.2  →   ^1.5.2
- @seriousme/openapi-schema-validator   ^2.1.2  →   ^2.1.5
- c8                                    ^9.0.0  →   ^9.1.0
- fastify                              ^4.23.2  →  ^4.25.2
- fastify-cli                           ^6.0.0  →   ^6.0.1

Security handlers fix for "AND" case

---

CHANGELOG.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
package-lock.json
package.json

- chore: removed husky as a dependency
- updated dependencies
- @biomejs/biome                        ^1.5.2  →   ^1.5.3
- @seriousme/openapi-schema-validator   ^2.1.5  →   ^2.2.1
- fastify                              ^4.25.2  →  ^4.26.1
- fastify-cli                           ^6.0.1  →   ^6.1.1

Update dependencies fastify 4.26.1

---

CHANGELOG.md
README.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
lib/ParserBase.js
package-lock.json
package.json
test/test-openapi.v3.json
test/test-plugin.v3.js

This feature adds the option to ignore a  route in an OpenApi specification, see README.md for details.

Feature: x-no-fastify-config

---

CHANGELOG.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
package-lock.json
package.json

- chore: updated dependencies
- @biomejs/biome                       ^1.9.0  →  ^1.9.4
- @seriousme/openapi-schema-validator  ^2.2.3  →  ^2.2.4
- fastify                              ^5.0.0  →  ^5.1.0
- fastify-cli                          ^7.0.0  →  ^7.0.1
- fastify-plugin                       ^5.0.0  →  ^5.0.1

chore: Updated dependencies Biome 1.9.4 etc

---

examples/generated-javascript-project/package.json
index.js

Closes #627
Impact to users should be negligeble. If they weren't awaiting their own `fastify.register` call, then there is no behavior difference. If they are awaiting their `fastify.register` call, they were probably expecting the routes to be loaded and ready right after.
Alternative solution, branch the code and only perform the await based on some new opt-in option.
Should I look at impact to this projects tests?

Add await to deterministically finish registering with fastify

---

CHANGELOG.md
bin/openapi-glue-cli.js
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
package-lock.json
package.json

- doc: added note on using schema 2020
- chore: updated dependencies
-  @seriousme/openapi-schema-validator  ^2.4.0  →  ^2.4.1
-  fastify                              ^5.2.2  →  ^5.3.2
-  fastify-cli                          ^7.3.0  →  ^7.4.0
-  minimist replaced by node:util.parseArgs

chore: replace minimist by node:util.parseArgs

---

CHANGELOG.md
docs/schema2020.md
examples/generated-javascript-project/package.json
examples/generated-standaloneJS-project/package.json
lib/Parser.js
package-lock.json
package.json
test/test-plugin.v2.js
test/test-plugin.v3.js

- feat: add support for OpenApi 3.2
- chore: updated dependencies
- @seriousme/openapi-schema-validator  ^2.4.4  →  ^2.7.0
- @biomejs/biome  ^2.2.0  →  ^2.2.4
- fastify         ^5.5.0  →  ^5.6.1

feat: add support for OpenApi 3.2
